---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-backtest-engine
  labels:
    app: stock-backtest-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock-backtest-engine
  template:
    metadata:
      labels:
        app: stock-backtest-engine
    spec:
      containers:
        - name: stock-backtest-engine
          image: stock-backtest-engine:latest
          ports:
            - containerPort: 8080
